### ISSUE TITLE
didActivateItem missing from SwiftUI implementation

### ISSUE THREAD

**Issue by thomasferiero** [dagronf/DSFQuickActionBar#1]
I might be missing something obvious, but I can't find how to use didActivateItem, didCancel etc. when following the Swift UI implementation.

How do I tell DSFQuickActionBar what to do when an item is activated?

**Comment by dagronf** [comment]
Hey mate, in the call to QuickActionBar<>, you pass in a binding to `selectedItem`. When that value changes, the item was activated.

For example, in the SwiftUI Demo in the `Demos/SwiftUI Demo` folder, if you look at [ContentView.swift, line 50](https://github.com/dagronf/DSFQuickActionBar/blob/a215330e25e87f5eecf928b252467be9be418037/Demos/SwiftUI%20Demo/SwiftUI%20Demo/ContentView.swift#L50) is the call for the quick action bar.

You can see at [line 54](https://github.com/dagronf/DSFQuickActionBar/blob/a215330e25e87f5eecf928b252467be9be418037/Demos/SwiftUI%20Demo/SwiftUI%20Demo/ContentView.swift#L54) we pass in a binding to a `selectedItem` object (in this case `selectedFilter`).

When `selectedFilter` changes, the user has activated the item.  You could detect the change in a callback by adding an `onChange` modifier to the quick action bar, like so :-

```swift
.onChange(of: selectedFilter) { newValue in
   Swift.print("Selected filter \(newValue)")
}
```

Hope that helps!

**Comment by thomasferiero** [comment]
Thanks a lot; that makes total sense and it's working as intended now. Great work on this, by the way!
