### ISSUE TITLE
quickActionBarDidCancel not being called when user clicks outside the bar

### ISSUE THREAD

**Issue by cyrilzakka** [dagronf/DSFQuickActionBar#3]
Hello, I hope you're well! I'm having an issue whereby after clicking outside the search bar, it stops showing up on subsequent calls, even though `isPresenting` is logging the correct values. 

In other words, `quickActionBarDidCancel` is called when the user pressed `esc` but not when clicking outside the bar. Currently being called as so:
```
self.quickActionBar.present(placeholderText: "Search...", width: self.screenWidth)
```

Otherwise when presenting the bar with the completion handler, the statement is logged, but the bar stop showing up on subsequent calls to present.
```
self.quickActionBar.present(placeholderText: "Search...", width: self.screenWidth) {
			Swift.print("Quick action bar closed")
}
```
Any help would be greatly appreciated!

**Comment by dagronf** [comment]
If your application is not frontmost (ie the window that accepts events), the quick action bar will not be presented (as the quick action bar window cannot become main window IF the application is not frontmost.)

Using the code you provided in [#2](https://github.com/dagronf/DSFQuickActionBar/issues/2), adding 

```swift
NSApp.activate(ignoringOtherApps: true)
```

to the start of the `toggleSearch` function solves the issue.

```swift
@objc func toggleSearch(_ sender: Any?) {

   NSApp.activate(ignoringOtherApps: true)

   if quickActionBar.isPresenting {
      // Hide
      quickActionBar.cancel()
   } else {
      // Show
      self.quickActionBar.present(
         parentWindow: nil,
         placeholderText: "Search Filters",
         searchImage: NSImage(systemSymbolName: "books.vertical", accessibilityDescription: "books.vertical"),
         width: min(800, max(500, 200 + 50))
      ) {
         Swift.print("Quick action bar closed")
      }
   }
}
```

Please let me know if this solves your issue.

**Comment by dagronf** [comment]
I'm not sure whether I should automatically call `NSApp.activate(...)` when presenting the window (is this more restrictive for the library user?)

**Comment by dagronf** [comment]
Okay I've added the call to the `present` method within the library.  If you update to the current latest version (4.2.1) this should resolve your issue.

**Comment by cyrilzakka** [comment]
Perfect thank you! I've made changes to the bar to make copy/paste/cut/select all work in the NSTextField even with a menu bar app. I've also modified the appearance (background and height) to make it match Spotlight Search a bit more. Would you like me to submit a pull request?

**Comment by dagronf** [comment]
Absolutely! I’d love to see what you’ve done.
